### ISSUE TITLE
Update Readme.md: Add how to use instructions and system requirements

### ISSUE THREAD

**Issue by moxerox** [MahmoudThePeltist/BOB-Node-Typescript-Bootstrapper#1]
provide at least the basic usage documentation with examples, then add more later.

**Comment by MahmoudThePeltist** [comment]
This is a good idea, it's currently still very barebones, but I'll add a short guide and perhaps a roadmap

**Comment by MahmoudThePeltist** [comment]
I think for now the new usage section is good enough, even though it's pretty short, if/when I add a CLI I'll make a more in-depth guide :)
